version: "3"
services:
  nginx:
    image: nginx:1.13-alpine
    container_name: nginx_container
    ports:
      - "80:8000"
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - api
  api:
    build: .
    container_name: JImages
    volumes:
      - ./app:/app
    expose:
      - "8000"
    restart: always
